name: Deploy to EC2

on:
  push:
    branches:
      - main  # o la rama que uses para producción

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ec2-user/mi-app  # cambia esto por el path de tu app
            git pull origin main
            # comandos de build o restart (ajusta según tu app):
            npm install        # si usas Node
            pm2 restart app    # si usas PM2
            # o python3 app.py, docker-compose up -d, etc.
          EOF
