name: Deploy to EC2

on:
  push:
    branches:
      - main  # o la rama que estés usando

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/mi-app  # cambia esto por el path de tu app
            git pull origin main
            npm install
            pm2 restart app  # o cualquier otro comando como docker-compose up -d
