name: Deploy to EC2

on:
  push:
    branches:
      - main  # Cambia si usas otra rama

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ec2-user/mi-app  # Asegúrate que esta ruta exista y tenga el repo clonado
            git pull origin main
            npm install                # Solo si usas Node.js
            pm2 restart app           # Reemplaza con tu comando si usas otro (como docker-compose, uvicorn, etc)
          EOF
